export type CrudFieldType = 'text' | 'number' | 'select' | 'switch' | 'date' | 'textarea';
export interface CrudField { code:string; label:string; type:CrudFieldType; required?:boolean; searchable?:boolean; table?:boolean; editable?:boolean; dictionary?:string; options?:{label:string;value:string|number|boolean}[] }
export interface CrudMetadata { resource:string; title:string; readPermission:string; writePermission:string; fields:CrudField[]; endpoints:{list:string;create:string;update:string;delete:string} }
const common=(resource:string,title:string,readPermission:string,writePermission:string,fields:CrudField[],list:string,create:string,update:string,del:string):CrudMetadata=>({resource,title,readPermission,writePermission,fields,endpoints:{list,create,update,delete:del}});
export const crudMetadata:Record<string,CrudMetadata>={
 customer:common('customer','客户管理','customer:read','customer:write',[{code:'name',label:'客户名称',type:'text',required:true,table:true,searchable:true},{code:'contact',label:'联系人',type:'text',table:true},{code:'phone',label:'联系电话',type:'text',table:true},{code:'status',label:'状态',type:'select',dictionary:'customer_status',table:true}],'/customers/page','/customers','/customers/{id}','/customers/{id}'),
 user:common('user','用户管理','system:user:read','system:user:write',[{code:'username',label:'用户名',type:'text',table:true},{code:'departmentId',label:'所属部门',type:'select',table:true},{code:'enabled',label:'状态',type:'switch',table:true}],'/system/users/page','/system/users','/system/users/{id}','/system/users/{id}'),
 role:common('role','角色管理','system:role:read','system:role:write',[{code:'roleCode',label:'角色编码',type:'text',table:true},{code:'roleName',label:'角色名称',type:'text',table:true},{code:'enabled',label:'状态',type:'switch',table:true}],'/system/roles/page','/system/roles','/system/roles/{id}','/system/roles/{id}'),
 menu:common('menu','菜单管理','system:menu:read','system:menu:write',[{code:'menuName',label:'菜单名称',type:'text',table:true},{code:'menuType',label:'类型',type:'select',table:true},{code:'permission',label:'权限标识',type:'text',table:true}],'/system/menus','/system/menus','/system/menus/{id}','/system/menus/{id}'),
 dictionary:common('dictionary','字典管理','system:user:read','system:user:write',[{code:'dictCode',label:'字典编码',type:'text',table:true},{code:'dictName',label:'字典名称',type:'text',table:true},{code:'enabled',label:'状态',type:'switch',table:true}],'/dictionaries','/dictionaries','/dictionaries/{code}','/dictionaries/{code}'),
 modeling:common('modeling','数据表建模','system:user:read','system:user:write',[{code:'tableCode',label:'表编码',type:'text',table:true},{code:'tableName',label:'表名称',type:'text',table:true},{code:'fields',label:'字段',type:'textarea'}],'/modeling/tables','/modeling/tables','/modeling/tables/{id}','/modeling/tables/{id}')
};
