<script setup lang="ts">
import { onMounted, ref } from 'vue';
import { ElMessage } from 'element-plus';
import CrudToolbar from '../../components/CrudToolbar.vue';
import { fetchDataTables, createDataTable, type DataTable } from '../../api/modeling';
import { fetchDictionaries } from '../../api/dictionary';
const tables = ref<DataTable[]>([]); const loading = ref(false); const dialog = ref(false);
const form = ref<any>({ tableCode: '', tableName: '', fields: [{ fieldCode: 'name', fieldType: 'STRING', required: true, sortOrder: 1, dictionaryCode: '' }] }); const dictionaries=ref<any[]>([]);
async function load() { loading.value = true; try { tables.value = (await fetchDataTables()).data.data; } catch { ElMessage.error('模型加载失败'); } finally { loading.value = false; } }
function addField() { form.value.fields.push({ fieldCode: '', fieldType: 'STRING', required: false, sortOrder: form.value.fields.length + 1, dictionaryCode: '' }); }
async function save() { try { await createDataTable(form.value); dialog.value = false; await load(); ElMessage.success('模型创建成功'); } catch { ElMessage.error('模型创建失败'); } }
onMounted(async()=>{await load();try{dictionaries.value=(await fetchDictionaries()).data.data}catch{}});
</script>
<template><el-card><template #header><CrudToolbar title="数据表建模"><el-button v-permission="'system:user:write'" type="primary" @click="dialog=true">新建业务表</el-button></CrudToolbar></template><el-table v-loading="loading" :data="tables" stripe><template #empty><el-empty description="暂无业务表模型"/></template><el-table-column prop="tableCode" label="表编码"/><el-table-column prop="tableName" label="表名称"/><el-table-column label="字段数"><template #default="{row}">{{row.fields?.length||0}}</template></el-table-column><el-table-column label="状态"><template #default="{row}"><el-tag :type="row.enabled?'success':'info'">{{row.enabled?'启用':'停用'}}</el-tag></template></el-table-column></el-table></el-card><el-dialog v-model="dialog" title="新建业务表" width="680px"><el-form label-width="80px"><el-form-item label="表编码"><el-input v-model="form.tableCode" placeholder="如 product"/></el-form-item><el-form-item label="表名称"><el-input v-model="form.tableName"/></el-form-item><el-divider>字段配置</el-divider><div v-for="(f,i) in form.fields" :key="i" class="field"><el-input v-model="f.fieldCode" placeholder="字段编码"/><el-select v-model="f.fieldType"><el-option label="字符串" value="STRING"/><el-option label="数字" value="NUMBER"/><el-option label="日期" value="DATE"/><el-option label="布尔" value="BOOLEAN"/></el-select><el-checkbox v-model="f.required">必填</el-checkbox></div><el-button link type="primary" @click="addField">+ 添加字段</el-button></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="save">保存模型</el-button></template></el-dialog></template><style scoped>.field{display:flex;gap:10px;margin-bottom:10px}.field .el-input{width:240px}.field .el-select{width:150px}</style>
