package com.moyucloud.modeling.service;
import com.moyucloud.modeling.domain.*; import com.moyucloud.modeling.dto.*; import org.springframework.stereotype.Service; import java.util.*;
@Service public class CrudCodeGeneratorService {
 public GeneratedModule generate(DataTableEntity t){String c=t.getTableCode(), cls=className(c); StringBuilder fs=new StringBuilder(), cols=new StringBuilder(), form=new StringBuilder(), sql=new StringBuilder("CREATE TABLE "+c+" (id CHAR(26) PRIMARY KEY");
  for(var f:t.getFields()){String jt=javaType(f.getFieldType()); fs.append("    private ").append(jt).append(" ").append(f.getFieldCode()).append(";\n"); cols.append("<el-table-column prop=\"").append(f.getFieldCode()).append("\" label=\"").append(f.getFieldCode()).append("\" />"); form.append("<el-form-item label=\"").append(f.getFieldCode()).append("\"><el-input v-model=\"form.").append(f.getFieldCode()).append("\" /></el-form-item>"); sql.append(", ").append(f.getFieldCode()).append(" ").append(sqlType(f.getFieldType())).append(f.isRequired()?" NOT NULL":"");} sql.append(");");
  String base="generated", entity="package "+base+".domain;\npublic class "+cls+"Entity {\n"+fs+"}\n", dto="package "+base+".dto;\npublic record "+cls+"Request("+t.getFields().stream().map(f->javaType(f.getFieldType())+" "+f.getFieldCode()).reduce((a,b)->a+","+b).orElse("")+") {}\n", repo="package "+base+".repository;\nimport org.springframework.data.jpa.repository.JpaRepository;\npublic interface "+cls+"Repository extends JpaRepository<"+cls+"Entity,String> {}\n", svc="package "+base+".service;\npublic class "+cls+"Service {}\n", ctl="@RestController @RequestMapping(\"/api/"+c+"\") public class "+cls+"Controller { @GetMapping public Object page(){return null;} @PostMapping public Object create(){return null;} @PutMapping(\"/{id}\") public Object update(){return null;} @DeleteMapping(\"/{id}\") public void delete(){} }\n", vue="<script setup lang=\"ts\">import {ref} from 'vue'; const rows=ref([]); const form=ref({}); const rules={};</script><template><el-table :data=\"rows\">"+cols+"</el-table><el-form :model=\"form\" :rules=\"rules\">"+form+"</el-form></template>", api="import {api} from './api'; export const fetch"+cls+"=(page=1,size=10)=>api.get('/"+c+"/page',{params:{page,size}}); export const create"+cls+"=(data:any)=>api.post('/"+c+"',data);", readme="# "+t.getTableName()+"\n\nGenerated CRUD module.\n", docker="services:\n  app:\n    build: .\n    ports: [\"8080:8080\"]\n";
  return new GeneratedModule(c,t.getTableName(),List.of(new GeneratedFile("backend/src/main/java/generated/domain/"+cls+"Entity.java",entity),new GeneratedFile("backend/src/main/java/generated/dto/"+cls+"Request.java",dto),new GeneratedFile("backend/src/main/java/generated/repository/"+cls+"Repository.java",repo),new GeneratedFile("backend/src/main/java/generated/service/"+cls+"Service.java",svc),new GeneratedFile("backend/src/main/java/generated/controller/"+cls+"Controller.java",ctl),new GeneratedFile("frontend/src/views/"+cls+"View.vue",vue),new GeneratedFile("frontend/src/api/"+c+".ts",api),new GeneratedFile("backend/src/main/resources/db/migration/V_generated_"+c+".sql",sql.toString()),new GeneratedFile("README.md",readme),new GeneratedFile("docker-compose.yml",docker))); }
 public boolean validate(GeneratedModule m){return m.files()!=null&&!m.files().isEmpty()&&m.files().stream().allMatch(f->f.content()!=null&&!f.content().isBlank());}
 private String className(String s){return Arrays.stream(s.split("_")).map(x->x.substring(0,1).toUpperCase()+x.substring(1)).reduce("",String::concat);} private String javaType(String t){return switch(t.toUpperCase()){case "NUMBER","INT","INTEGER"->"Integer";case "BOOLEAN"->"Boolean";case "DATE"->"LocalDate";default->"String";};} private String sqlType(String t){return switch(t.toUpperCase()){case "NUMBER","INT","INTEGER"->"INT";case "BOOLEAN"->"BOOLEAN";case "DATE"->"DATE";default->"VARCHAR(255)";};}
}
