package com.moyucloud.modeling.controller;

import com.moyucloud.auth.service.*;
import com.moyucloud.modeling.dto.*;
import com.moyucloud.modeling.repository.DataTableRepository;
import com.moyucloud.modeling.service.CrudCodeGeneratorService;
import com.moyucloud.shared.ApiResponse;
import jakarta.validation.Valid;
import java.util.*;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/api/projects")
public class ProjectWizardController {
    private final DataTableRepository repo;
    private final CrudCodeGeneratorService gen;
    private final AuthService auth;

    public ProjectWizardController(
            DataTableRepository r, CrudCodeGeneratorService g, AuthService a) {
        repo = r;
        gen = g;
        auth = a;
    }

    @PostMapping("/preview")
    public ApiResponse<Map<String, String>> preview(
            @RequestHeader(value = "Authorization", required = false) String a,
            @Valid @RequestBody ProjectWizardRequest r) {
        auth.requirePermission(a, PermissionCodes.SYSTEM_USER_WRITE);
        Map<String, String> out = new LinkedHashMap<>();
        out.put("README.md", "# " + r.projectName() + "\n\nGenerated by MoYu-Cloud.\n");
        out.put(
                "docker-compose.yml",
                "services:\n  app:\n    build: .\n    ports: [\\\"8080:8080\\\"]\n");
        out.put(
                "application.yml",
                "spring:\n  datasource:\n    url: "
                        + Optional.ofNullable(r.databaseUrl())
                                .orElse("jdbc:mysql://localhost:3306/app")
                        + "\n");
        return ApiResponse.success(out);
    }
}
